### PR TITLE
Update language descriptions and links

### PR DESCRIPTION
**Pull request by novusnota**
## Why is it important?

* Added a link to Tact docs from the sidebar
* Updated the description of Tact language (both English and Chinese)
* Unified sidebar and navbar link order, from the most high-level (such as Tact and Tolk) to the most low-level (such as Fift and TL-B). That makes all languages easies to discover and visually conveys the idea of "digging deep" and learning more.

## Preview

image

### CODE REVIEW

**Comment by novusnota** [comment]
Simplified and shrank the description to better match the rest of the page:

image

**Comment by novusnota** [comment]
...And now edited to be more formal and clear:

image_2024-11-05_16-25-58

**Comment by novusnota** [comment]
@reveloper If the order from higher to lower-level languages doesn't feel right to you, we can inverse it and go from lower (TL-B and Fift) to higher (Tolk and Tact). But I assumed that placing more accessible languages first (Tact and Tolk) would be more beneficial to users, hence this sorting.

That said, the _current_ order is just a seemingly random shuffle:

image

**Comment by reveloper** [comment]
@novusnota your language order seems more convenient according to the developer community position. 
Thank you!

**Pull request merged**
