### PR TITLE
Add link for Rust SDK

### PR DESCRIPTION
**Pull request by Apapirovskiy**
Added link to open source Rust SDK for The Open Network made by ston.fi 

## Why is it important?

Open source solution for the TON community

### CODE REVIEW

**Comment by reveloper** [comment]
Hello, @Apapirovskiy! 

Please correct me if I am wrong. Is this SDK more related to the general SDK list for dApps development (link (https://docs.ton.org/develop/dapps/#most-popular-sdk))? If you agree, please add this link to the page.

**Comment by Apapirovskiy** [comment]
Updated

**Comment by reveloper** [comment]
Could you exclude the previous link from adnl.md?

**Comment by Apapirovskiy** [comment]
Done

**Comment by Gusarich** [comment]
@reveloper is it good now? should we merge?

**Comment by reveloper** [comment]
@Apapirovskiy thank you!

**Pull request merged**
