### PR TITLE
Fix tvm exit codes

### PR DESCRIPTION
**Pull request by tvorogme**
```
"Asm.fif" include

<{ 0 PUSHINT SETGASLIMIT 0 PUSHINT }>s runvmcode
."Exit code: " (dump) type drop cr
```

### CODE REVIEW

**Comment by Gusarich** [comment]
@tvorogme why not include this exit code in the main list? Is it necessary to move it as a separate one at the very bottom?

**Comment by Gusarich** [comment]
> The `-14` exit code actually is `13` exit code, but with logical NOT. It's specific case... Don't know how to do it properly

I think if it's the only one negative code, it'll be fine to put it at the bottom. Are there any more negative exit codes?

**Comment by tvorogme** [comment]
I've not founded more :)

**Comment by Gusarich** [comment]
Okay, merging then!

**Comment by tvorogme** [comment]
@Gusarich fixed

**Pull request merged**
