### PR TITLE
 #306 dex swap by @ton.md

### PR DESCRIPTION
**Pull request by mbaneshi**

### CODE REVIEW

**Comment by reveloper** [comment]
@mbaneshi, looks great! Could you add little fixes for the following:

-  Could you please add clarification about `sender` for this example - where from and how you should get this 
 - Please, check and fix little typos.

**Comment by Gusarich** [comment]
@mbaneshi Thank you for the contribution!
However, let's fix some minor issues with it first.
 * you use `sender` variable multiple times but don't show how to get it
 * there are lots of little mistakes with letter registers, spaces etc. would be nice to fix them too

**Comment by mbaneshi** [comment]
@Gusarich Thanks 🙏.
Sure , I will revise and correct them.

**Comment by mbaneshi** [comment]
Hi @Gusarich 
I think, it is done, would you please check it? Thank you.

**Comment by Gusarich** [comment]
might need some more polishing, but I think we can merge it now

**Review by Gusarich — APPROVED** [review]

**Comment by reveloper** [comment]
@mbaneshi, @Gusarich, Thank you!

**Comment by mbaneshi** [comment]
@reveloper thank you too, this is my first merge contribution, and I am excited

**Pull request merged**
