### PR TITLE
add more example links in jetton processing page

### PR DESCRIPTION
**Pull request by MKdir98**
## Why is it important?

I just linked Tontools(python) and Tonjs(js) examples on this page and the go and Tokenweb version was that

## Related Issue
https://github.com/ton-community/ton-docs/issues/353 

My telegram ID: [MK_dir98](https://t.me/MK_dir98)

### CODE REVIEW

**Comment by MKdir98** [comment]
I just do a simple thing. I wasn't sure about what the task said. Please if I need to anything for this tell me.

**Comment by reveloper** [comment]
@MKdir98, I am delighted you’re participating! 

The goal of this task is to add direct code snippets to the guide page because links are very hard to read. I understand, that sometimes code snippets are too big, but we can find a balance between direct code blocks and links to the full reference and improve readability of our guides.

[Here](https://docs.ton.org/develop/dapps/cookbook#how-to-construct-a-message-for-a-jetton-transfer-with-a-comment) you can see tabs implementation, it will be available for .mdx* format with <tab></tab> items. You also can learn this in the source file - [here](https://github.com/ton-community/ton-docs/blob/main/docs/develop/dapps/cookbook.md?plain=1#L246).

Please, let me know if you face any issues with tabs.
Thank you!

**Comment by MKdir98** [comment]
Oh, you're right. I'll fix it

**Comment by reveloper** [comment]
@MKdir98, do You have plans to update this PR?

**Comment by MKdir98** [comment]
> @MKdir98, do You have plans to update this PR?

Oops I forgot this. I'll keep you posted about this.

**Comment by reveloper** [comment]
Great, this looks much better! 

Thank you for your time, @MKdir98!

**Pull request merged**
