### PR TITLE
Update crc32.md content, adding Typescript example

### PR DESCRIPTION
**Pull request by howardpen9**
## Why is it important?

To better understand, adding TS example to get the code.

## Related Issue

NONE

### CODE REVIEW

**Comment by Gusarich** [comment]
Thanks for the PR!
There are also some rules to apply a bitmask on a resulting hash to get the opcode (either request or response). Here is how I did it in crc32-opcode-helper extension for vs code:
```
function calculateRequestOpcode(str: string): string {
    return (BigInt(crc32.str(str)) & BigInt(0x7fffffff)).toString(16);
}

function calculateResponseOpcode(str: string): string {
    const a = BigInt(crc32.str(str));
    const b = BigInt(0x80000000);
    return ((a | b) < 0 ? (a | b) + BigInt('4294967296') : a | b).toString(16);
}
```

**Comment by howardpen9** [comment]
nice! Understood.

**Comment by howardpen9** [comment]
Update

**Comment by reveloper** [comment]
@howardpen9, Thank you!

**Pull request merged**
