### PR TITLE
TON DNS resolvers article

### PR DESCRIPTION
**Pull request by ProgramCrafter**
## Why is it important?

Currently, documentation does not feature how to build subdomain resolvers for TON DNS, and for existing resolvers (auto-dns and manual-dns) it only links to code, hindering technology adoption.

## Related Issue

https://github.com/ton-society/ton-footsteps/issues/251

### CODE REVIEW

**Comment by Gusarich** [comment]
@ProgramCrafter why did you change the sidebar so much?

**Comment by ProgramCrafter** [comment]
Force-pushed to fix the mess with sidebar. Seems normal now.

**Comment by ProgramCrafter** [comment]
The article is done.

It would be nice to shorten the block with full code of subdomain resolver (see Appendix 1) so that it could be expanded by mouse click. However, I don't know the corresponding MDX component if it even exists.

**Comment by reveloper** [comment]
@ProgramCrafter thank you for your contribution!
1. It would be nice if you add references to other section of the documentation and standards related to the guide's theme. 
2. You can create a spoiler for the Docusaurus docs with the following:

```
<details>
  <summary><b>Show the entire list</b></summary>
  content
</details>
```

**Pull request merged**
