### PR TITLE
Fix typo in documentation related to TonConnect demo telegram bot project

### PR DESCRIPTION
**Pull request by num13ru**
## Why is it important?

This pull request corrects a typo in the documentation of the TonConnect demo telegram bot project. The typo is in the variable name `WALLETS_LIST_CAHCE_TTL_MS`, which should be `WALLETS_LIST_CACHE_TTL_MS`. This correction is important for clarity and to ensure that the documentation accurately reflects the codebase.

## Related Issue

This pull request is related to a previous contribution (https://github.com/ton-connect/demo-telegram-bot/pull/2) where the typo in the code was fixed. This current pull request aims to update the documentation accordingly to maintain consistency between the code and the documentation.

### CODE REVIEW

**Comment by reveloper** [comment]
@num13ru, hello, thank you for your contribution! Can you switch this to the final PR? I can't merge the draft PR.

**Comment by num13ru** [comment]
Ok thanks! 
Also I'm still waiting approve and merge in the original repo (https://github.com/ton-connect/demo-telegram-bot/pull/2) :)

**Comment by reveloper** [comment]
@num13ru Is this block this PR? I have no permissions in the ton-connect repo.

**Comment by num13ru** [comment]
Yes it blocks
@siandreev please see https://github.com/ton-connect/demo-telegram-bot/pull/2 🙏

**Review by xgizam77 — APPROVED** [review]

**Review by xgizam77 — APPROVED** [review]

**Comment by num13ru** [comment]
@reveloper ready to go!
https://github.com/ton-connect/demo-telegram-bot/pull/2 merged

**Comment by reveloper** [comment]
@num13ru, @siandreev Thank you!

**Pull request merged**
