### PR TITLE
TVM Instruction Search Component for TON Docs

### PR DESCRIPTION
**Pull request by krau5**
Closes [#175](https://github.com/ton-society/ton-footsteps/issues/175).

### CODE REVIEW

**Comment by thekiba** [comment]
Hello @krau5, I hope this message finds you well. 

The current implementation of the TVM Instruction Search React Component has removed the original structure of categories and tables with opcodes, leaving only a search field. This is not the desired outcome. In addition, the search feature only works with opcodes, not all the information contained in the tables.

Please make the following changes to correct the issue:
1. Restore the original structure of categories and tables with opcodes as it was before the implementation of the search component. The search feature should be an additional tool, not a replacement for the existing structure.
2. Modify the search functionality to not only search by opcodes but also by all other information contained in the tables, such as Fift syntax, Stack, Description, and Gas.

Thank you for your attention to this matter. We believe these changes will greatly improve the functionality and user experience of the TON Documentation website.

If you have any questions or need assistance, please feel free to reach out. If you require further clarification or need to discuss additional matters, you can also contact me directly via Telegram. My username is the same as my GitHub username.

**Comment by krau5** [comment]
Hey @thekiba, thanks for the feedback!
Sure, I'll make fixes accordingly ASAP. The search field will be placed above the table with opcodes

**Comment by thekiba** [comment]
Hi @krau5,

I've made some changes to the code, which I believe will help address the issue we discussed. Specifically, I've updated the styling to match the table format shown below, and I've also modified the search functionality to be case-insensitive. Everything else looks good.

I've created a patch for your review, which you can find attached to this comment.

To apply the patch, please follow these steps:

1. Download the attached [0001-docs-adding-styles-to-the-search-result.patch](https://github.com/ton-community/ton-docs/files/11120639/0001-docs-adding-styles-to-the-search-result.patch) file.
2. Ensure that your local branch is synchronized with the PR branch on GitHub.
3. Apply the patch using the following command in your terminal:

```bash
git apply 0001-docs-adding-styles-to-the-search-result.patch
```

After applying the patch, you should see the changes I made in your code. Please review the changes, and if you find them suitable, feel free to include them in your PR.

To expedite the review process after applying the patch, you can simply attach screenshots of the updated table and search functionality to your PR.

Let me know if you have any questions or need further clarification. I'd be more than happy to help!

**Comment by krau5** [comment]
Hi @thekiba 

I have applied the patch file and the PR has been updated as well, case-insensitive search works along with the updated tables as you can see on a screenshot. I have also removed unused code since the results were updated.
Thanks for such a help!

image

**Comment by thekiba** [comment]
I'm glad to hear that the patch worked well and the updated table and case-insensitive search functionality meet your expectations. It's great that you've also taken the time to clean up any unused code.

If you have any further questions or need assistance in the future, please don't hesitate to reach out. I'm always here to help!

Good luck with your PR and the project!

**Comment by SwiftAdviser** [comment]
Thank you very much @krau5 and @thekiba!

**Pull request merged**
